/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sysasistencia.angeldx.view;
import java.util.ArrayList;
import java.util.Calendar; 
import javax.swing.JOptionPane;
import sysasistencia.angeldx.common.Funciones;
import sysasistencia.angeldx.manager.ControlManager;
import sysasistencia.angeldx.manager.EventoManager;
import sysasistencia.angeldx.to.ControlTO;
import sysasistencia.angeldx.to.EstudianteTO;
import sysasistencia.angeldx.to.EventoTO;
import sysasistencia.angeldx.to.ParticipanteTO;
/**
 *
 * @author AngelDX
 */
public class frmAsistenciaAdd extends javax.swing.JFrame {
java.util.Calendar calendario; 
int dia, dias, mes, año, hora, hora24, minutos, segundos, meridiano; 
String m;
EventoManager evento=new EventoManager();
ControlManager control=new ControlManager();
ControlTO data=new ControlTO();
EstudianteTO est=new EstudianteTO();
ParticipanteTO part=new ParticipanteTO();
    /**
     * Creates new form frmAsistenciaAdd
     */
    public frmAsistenciaAdd() {
        initComponents();    
        setTitle("Registro de Asistencia | SiSAsistent 1.0");
        setExtendedState(MAXIMIZED_BOTH);
        reloj(); 
        cargarEventos();
        txtCodigo.requestFocus();
        btnRegistar.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        optEntrada = new javax.swing.JRadioButton();
        optSalida = new javax.swing.JRadioButton();
        cboEvento = new javax.swing.JComboBox();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblMensaje = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnRegistar = new javax.swing.JButton();
        lblCarrera1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblHora.setBackground(new java.awt.Color(0, 0, 0));
        lblHora.setFont(new java.awt.Font("Arial", 3, 80)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 51, 51));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHora.setText("Hora");

        lblFecha.setBackground(new java.awt.Color(51, 51, 255));
        lblFecha.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblFecha.setText("Fecha");
        lblFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        buttonGroup1.add(optEntrada);
        optEntrada.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        optEntrada.setSelected(true);
        optEntrada.setText("Entrada");

        buttonGroup1.add(optSalida);
        optSalida.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        optSalida.setText("Salida");

        cboEvento.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(optEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(optSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(cboEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(optEntrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(optSalida)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        lblCodigo.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCodigo.setText("Codigo");

        lblNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Apellidos Y Nombres");

        lblMensaje.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        lblMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensaje.setText("Mensaje");

        txtCodigo.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        txtCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
        });

        btnRegistar.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        btnRegistar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sysasistencia/icons/PNG-48/clock.png"))); // NOI18N
        btnRegistar.setText("Registrar");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });

        lblCarrera1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        lblCarrera1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCarrera1.setText("Carrera");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 490, Short.MAX_VALUE)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(520, 520, 520))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblMensaje, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1319, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(567, 567, 567)
                .addComponent(btnRegistar, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCarrera1, javax.swing.GroupLayout.DEFAULT_SIZE, 1319, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistar)
                .addGap(33, 33, 33)
                .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCarrera1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
        // TODO add your handling code here:
        String tipo="";
        if(evt.getKeyCode()==10){//SI SE PRESIONA ENTER
          if(txtCodigo.getText().length()==9){ 
            est=control.buscarEstudiante(txtCodigo.getText()); 
           if(est.getId()!=0){ //Estudiante esta registrado en la base de datos               
            lblNombre.setText(est.getNombre());
            lblCodigo.setText(est.getCodigo());
            lblCarrera1.setText(Funciones.carreraFull(est.getCarrera()));
            String evento[]=((String)cboEvento.getSelectedItem()).split("-"); 
            if(optEntrada.isSelected()){
                tipo="ENTRADA";
            }
            if(optSalida.isSelected()){
                tipo="SALIDA";
            }
            //Verificar si ya ingreso al evento para no registrar nuevamente su ingreso
                if(control.verificarRegistro(est.getId(),Integer.parseInt(evento[0]),tipo)){
                    lblMensaje.setText("Su ingreso esta Registrado anteriormente");
                    JOptionPane.showMessageDialog(null,"¡Su ingreso esta Registrado anteriormente!");
                    btnRegistar.setEnabled(false);
                }else{
                    //lblMensaje.setText("Bienvenido, Presione el boton Registrar"); 
                    //btnRegistar.setEnabled(true);
                    //String evento[]=((String)cboEvento.getSelectedItem()).split("-");
                    data.setEstudiante_id(est.getId());
                    data.setEvento_id(Integer.parseInt(evento[0]));
                    data.setFechahora(año+"-"+mes+"-"+dia+" "+hora24+":"+minutos+":"+segundos);
                    if(optEntrada.isSelected()){
                        data.setTipo("ENTRADA");
                    }
                    if(optSalida.isSelected()){
                        data.setTipo("SALIDA");
                    }

                    if(control.registarControl(data)){
                        //JOptionPane.showMessageDialog(null,"Asistencia registrada"); 
                        lblMensaje.setText("Asistencia registrada");
                        btnRegistar.setEnabled(false);
                    }else{
                        JOptionPane.showMessageDialog(null,"No se registro la Asistencia");
                    }
                        txtCodigo.requestFocus();
                        //lblCarrera1.setText("");
                        //lblCodigo.setText("");
                        //lblMensaje.setText("");
                        //lblNombre.setText("");
                }            
           }else{
            lblNombre.setText("Estudiante no encontrado...");
           }
           txtCodigo.setText("");
           txtCodigo.requestFocus();
          }else{
            part=control.buscarParticipante(txtCodigo.getText());
            if(part.getId()!=0){ //Participante esta registrado en la base de datos               
            lblNombre.setText(part.getNombre());
            lblCodigo.setText(String.valueOf(part.getId()));
            lblCarrera1.setText(part.getEntidad());
            String evento[]=((String)cboEvento.getSelectedItem()).split("-"); 
            if(optEntrada.isSelected()){
                tipo="ENTRADA";
            }
            if(optSalida.isSelected()){
                tipo="SALIDA";
            }
            //Verificar si ya ingreso al evento para no registrar nuevamente su ingreso
                if(control.verificarRegistroPart(part.getId(),Integer.parseInt(evento[0]),tipo)){
                    lblMensaje.setText("Su ingreso esta Registrado anteriormente");
                    JOptionPane.showMessageDialog(null,"¡Su ingreso esta Registrado anteriormente!");
                    btnRegistar.setEnabled(false);
                }else{                    
                    data.setParticipante_id(part.getId());
                    data.setEvento_id(Integer.parseInt(evento[0]));
                    data.setFechahora(año+"-"+mes+"-"+dia+" "+hora24+":"+minutos+":"+segundos);
                    if(optEntrada.isSelected()){
                        data.setTipo("ENTRADA");
                    }
                    if(optSalida.isSelected()){
                        data.setTipo("SALIDA");
                    }

                    if(control.registarControlPart(data)){
                        //JOptionPane.showMessageDialog(null,"Asistencia registrada"); 
                        lblMensaje.setText("Asistencia registrada");
                        btnRegistar.setEnabled(false);
                    }else{
                        JOptionPane.showMessageDialog(null,"No se registro la Asistencia");
                    }
                        txtCodigo.requestFocus();
                        //lblCarrera1.setText("");
                        //lblCodigo.setText("");
                        //lblMensaje.setText("");
                        //lblNombre.setText("");
                }            
           }else{
            lblNombre.setText("Participante no encontrado...");
           }
           txtCodigo.setText("");
           txtCodigo.requestFocus();
          }
        }
        
    }//GEN-LAST:event_txtCodigoKeyReleased

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        // TODO add your handling code here:
        String evento[]=((String)cboEvento.getSelectedItem()).split("-");
            data.setEstudiante_id(est.getId());
            data.setEvento_id(Integer.parseInt(evento[0]));
            data.setFechahora(año+"-"+mes+"-"+dia+" "+hora24+":"+minutos+":"+segundos);
            if(optEntrada.isSelected()){
                data.setTipo("ENTRADA");
            }
            if(optSalida.isSelected()){
                data.setTipo("SALIDA");
            }
            
            if(control.registarControl(data)){
                JOptionPane.showMessageDialog(null,"Asistencia registrada..."); 
                btnRegistar.setEnabled(false);
            }else{
                JOptionPane.showMessageDialog(null,"No se registro la Asistencia");
            }
                txtCodigo.requestFocus();
                lblCarrera1.setText("");
                lblCodigo.setText("");
                lblMensaje.setText("");
                lblNombre.setText("");
    }//GEN-LAST:event_btnRegistarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAsistenciaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAsistenciaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAsistenciaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAsistenciaAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAsistenciaAdd().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboEvento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCarrera1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JRadioButton optEntrada;
    private javax.swing.JRadioButton optSalida;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
    private void reloj() { 
        calendario = new java.util.GregorianCalendar(); 
        segundos = calendario.get(Calendar.SECOND); 
        javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() { 
        @ Override 
        public void actionPerformed(java.awt.event.ActionEvent ae) { 
            java.util.Date actual = new java.util.Date(); 
            calendario.setTime(actual); 
            dia = calendario.get(Calendar.DAY_OF_MONTH); 
            dias=calendario.get(Calendar.DAY_OF_WEEK);
            mes = (calendario.get(Calendar.MONTH) + 1); 
            año = calendario.get(Calendar.YEAR); 
            hora = calendario.get(Calendar.HOUR);
            hora24 = calendario.get(Calendar.HOUR_OF_DAY);
            minutos = calendario.get(Calendar.MINUTE); 
            segundos = calendario.get(Calendar.SECOND); 
            meridiano=calendario.get(Calendar.AM_PM);
            m=(meridiano==0)?"AM":"PM";
            //JOptionPane.showMessageDialog(rootPane, m);
            String hour = String.format("%02d : %02d : %02d %s", hora, minutos, segundos, m); 
            String date = String.format("%s, %02d de %s del %02d",Funciones.diaLetras(String.valueOf(dias)), dia, Funciones.mesLetras(String.valueOf(mes)), año); 
            lblHora.setText("<html><center>" +hour+"</center></html>"); 
            lblFecha.setText("<html><p>"+date+"</p></html>");
        } 
        }); 
        timer.start(); 
    }
    
    private void cargarEventos() {
        try {
            ArrayList<EventoTO> lista=new ArrayList();
            lista=evento.listar();            
            for(EventoTO x:lista){
                cboEvento.addItem(x.getId()+"-"+x.getDescripcion());
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
}
